const Metric = ({ value, label }: { value: string; label: string }) => (
  <div className="metric"><strong>{value}</strong><span>{label}</span></div>
);

const Rating = ({ value, label }: { value: number; label: string }) => (
  <div className="rating"><span>{label}</span><div>{[1, 2, 3, 4, 5].map((n) => <i key={n} className={n <= value ? "on" : ""} />)}</div></div>
);

export default function Home() {
  return (
    <main>
      <nav className="topbar"><a className="brand" href="#start">let’s go!</a><div className="navlinks"><a href="#idea">идея</a><a href="#flow">как работает</a><a href="#mvp">MVP</a></div><a className="pill small" href="#final">погнали ↘</a></nav>
      <section className="slide hero" id="start"><div className="eyebrow">бот для тех, кто всё собирается</div><h1>let’s<br/><em>go!</em></h1><p className="lead">Превращаем «когда-нибудь надо»<br/>в ваши общие воспоминания.</p><div className="sticker">не список дел.<br/><b>список приключений.</b></div><a className="down" href="#idea" aria-label="Дальше">↓</a></section>
      <section className="slide problem" id="idea"><div className="section-no">01 / ЗАЧЕМ</div><h2>Идей много.<br/>Случается — <span>мало.</span></h2><div className="problem-grid"><p>Мы постоянно говорим: «надо съездить», «давайте попробуем», «когда-нибудь сделаем».</p><p className="accent-card">let’s go! хранит эти идеи, помогает выбрать одну и доводит компанию до действия.</p></div><div className="ticker"><span>ДОБАВИЛИ → ВЫБРАЛИ → ЗАПЛАНИРОВАЛИ → СДЕЛАЛИ → ВСПОМНИЛИ → ДОБАВИЛИ → ВЫБРАЛИ →</span></div></section>
      <section className="slide" id="flow"><div className="section-no">02 / МЕХАНИКА</div><h2>Пять шагов.<br/>Одна хорошая история.</h2><div className="steps"><article><b>01</b><h3>Собираем</h3><p>Каждый добавляет идею — открыто или анонимно.</p></article><article><b>02</b><h3>Оцениваем</h3><p>Сложность, бюджет и длительность — от 1 до 5.</p></article><article><b>03</b><h3>Голосуем</h3><p>Компания выбирает следующее приключение.</p></article><article><b>04</b><h3>Планируем</h3><p>Сразу назначаем дату, время и участников.</p></article><article><b>05</b><h3>Доказываем</h3><p>Все подтверждают, кто-то добавляет фото.</p></article></div></section>
      <section className="slide idea-card-slide"><div className="section-no light">03 / КАРТОЧКА ИДЕИ</div><div className="idea-card"><div className="anonymous">🎲 автор скрыт</div><h2>Уехать на выходные<br/>в случайный город</h2><div className="ratings"><Rating label="сложность" value={3}/><Rating label="бюджет" value={4}/><Rating label="длительность" value={5}/></div><button>добавить в голосование ↗</button></div><p className="side-note">Никаких длинных анкет.<br/>Три понятные шкалы помогают найти активность под конкретный вечер.</p></section>
      <section className="slide plan-slide"><div className="section-no">04 / ПОСЛЕ ГОЛОСОВАНИЯ</div><div className="winner">победила идея 🎉</div><h2>Сначала дата.<br/>Потом напоминание.</h2><div className="calendar-card"><div><small>СУББОТА</small><strong>24</strong><span>августа · 18:00</span></div><div className="people"><i>А</i><i>М</i><i>С</i><i>+2</i></div><p>Бот напомнит за день, в день встречи и после мероприятия.</p></div></section>
      <section className="slide proof-slide"><div className="section-no light">05 / ЧЕСТНАЯ АЧИВКА</div><h2>Сделано —<br/>значит доказано.</h2><div className="proof-grid"><div className="check-card"><span>Подтверждения</span><b>4 из 4</b><i>✓</i></div><div className="check-card"><span>Фотография</span><b>добавлена</b><i>✓</i></div></div><p className="proof-rule">Ачивка выдаётся, только когда <u>все участники подтвердили выполнение</u> и загружено хотя бы одно фото.</p><div className="achievement">🏆 активность выполнена</div></section>
      <section className="slide archive-slide"><div className="section-no">06 / АРХИВ</div><h2>Не галочки.<br/><span>Воспоминания.</span></h2><div className="stats"><Metric value="14" label="выполнено"/><Metric value="27" label="ждут своего часа"/><Metric value="3" label="месяца подряд"/></div><div className="memory-wall"><div className="memory orange">ночной<br/>пикник <small>12.07</small></div><div className="memory blue">случайный<br/>город <small>03.08</small></div><div className="memory lime">ужин<br/>вслепую <small>17.08</small></div></div></section>
      <section className="slide mvp-slide" id="mvp"><div className="section-no">07 / ПЕРВАЯ ВЕРСИЯ</div><h2>Небольшой бот.<br/>Полный цикл.</h2><ol className="mvp-list"><li><span>01</span>Компания и ссылка-приглашение</li><li><span>02</span>Идеи и оценки от 1 до 5</li><li><span>03</span>Голосование и случайный выбор</li><li><span>04</span>Дата, участники и напоминания</li><li><span>05</span>Подтверждения, фото и ачивка</li><li><span>06</span>Общий архив приключений</li></ol></section>
      <section className="slide final-slide" id="final"><p>ну что?</p><h2>let’s<br/><em>go!</em></h2><div className="final-copy">Создаём свою компанию.<br/>Записываем первые десять идей.<br/><b>И начинаем делать.</b></div><a className="pill final-pill" href="#start">с начала ↑</a></section>
    </main>
  );
}
